#############################################################################
# Makefile for building: vplay
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Apr 3 22:27:20 2013
# Project:  vplay.pro
# Template: app
# Command: /opt/local/v-play/Desktop/Qt/4.8.1/gcc/bin/qmake -o Makefile vplay.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DPLATFORM_MAC -DQML_PLATFORM_PATH=/opt/local/v-play/Desktop/Qt/4.8.1/gcc/../../../V-PlaySDK/plugins/macx -DQML_GENERIC_PATH=/opt/local/v-play/Desktop/Qt/4.8.1/gcc/../../../V-PlaySDK/plugins/generic -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/default -I. -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/include/QtCore -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/include/QtGui -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtDeclarative.framework/Versions/4/Headers -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/include/QtDeclarative -I/opt/local/v-play/Desktop/Qt/4.8.1/gcc/include -I/opt/local/v-play/Desktop/V-PlaySDK/include -I. -F/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib -L/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib -framework Cocoa -framework OpenGL -framework OpenAL -framework AudioToolbox -L/opt/local/v-play/Desktop/Qt/4.8.1/gcc/../../../V-PlaySDK/lib/third_party -lcurl -lfreetype -ljpeg -lpng14 -lxml2 -lz -L/opt/local/v-play/Desktop/Qt/4.8.1/gcc/../../../V-PlaySDK/lib -lVPlay_debug -framework QtDeclarative -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtScript -framework QtCore -framework QtSvg -framework QtGui -framework QtSql -framework QtXmlPatterns -framework QtNetwork 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/v-play/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = vplay.cpp \
		qmlapplicationviewer.cpp moc_vplay.cpp \
		moc_qmlapplicationviewer.cpp \
		qrc_vplay.cpp
OBJECTS       = vplay.o \
		qmlapplicationviewer.o \
		moc_vplay.o \
		moc_qmlapplicationviewer.o \
		qrc_vplay.o
DIST          = /opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		projectinclude.pri \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		vplay.pro
QMAKE_TARGET  = vplay
DESTDIR       = 
TARGET        = vplay

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vplay.pro  /opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/default/qmake.conf /opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		projectinclude.pri \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtDeclarative.framework/QtDeclarative.prl \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtScript.framework/QtScript.prl \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtSvg.framework/QtSvg.prl \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtSql.framework/QtSql.prl \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtXmlPatterns.framework/QtXmlPatterns.prl \
		/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -o Makefile vplay.pro
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
projectinclude.pri:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtDeclarative.framework/QtDeclarative.prl:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtScript.framework/QtScript.prl:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtSvg.framework/QtSvg.prl:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtSql.framework/QtSql.prl:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtXmlPatterns.framework/QtXmlPatterns.prl:
/opt/local/v-play/Desktop/Qt/4.8.1/gcc/lib/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile vplay.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vplay1.0.0 || $(MKDIR) .tmp/vplay1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vplay1.0.0/ && $(COPY_FILE) --parents vplay.h qmlapplicationviewer.h .tmp/vplay1.0.0/ && $(COPY_FILE) --parents vplay.qrc .tmp/vplay1.0.0/ && $(COPY_FILE) --parents vplay.cpp qmlapplicationviewer.cpp .tmp/vplay1.0.0/ && (cd `dirname .tmp/vplay1.0.0` && $(TAR) vplay1.0.0.tar vplay1.0.0 && $(COMPRESS) vplay1.0.0.tar) && $(MOVE) `dirname .tmp/vplay1.0.0`/vplay1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vplay1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_vplay.cpp moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_vplay.cpp moc_qmlapplicationviewer.cpp
moc_vplay.cpp: qmlapplicationviewer.h \
		/opt/local/v-play/Desktop/V-PlaySDK/include/vplayapplication.h \
		vplay.h
	/opt/local/v-play/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ vplay.h -o moc_vplay.cpp

moc_qmlapplicationviewer.cpp: qmlapplicationviewer.h
	/opt/local/v-play/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

compiler_rcc_make_all: qrc_vplay.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_vplay.cpp
qrc_vplay.cpp: vplay.qrc \
		vplay.png
	/opt/local/v-play/Desktop/Qt/4.8.1/gcc/bin/rcc -name vplay vplay.qrc -o qrc_vplay.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

vplay.o: vplay.cpp vplay.h \
		qmlapplicationviewer.h \
		/opt/local/v-play/Desktop/V-PlaySDK/include/vplayapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vplay.o vplay.cpp

qmlapplicationviewer.o: qmlapplicationviewer.cpp qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer.cpp

moc_vplay.o: moc_vplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vplay.o moc_vplay.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

qrc_vplay.o: qrc_vplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_vplay.o qrc_vplay.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

